# Generated by Django 2.2.4 on 2019-08-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190826_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/users'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_phone',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
